"""add country dimension

Revision ID: 10ebf8c7fd12
Revises: cf24976e419a
Create Date: 2026-07-18 02:20:58.414942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ebf8c7fd12'
down_revision: Union[str, Sequence[str], None] = 'cf24976e419a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_country',
    sa.Column('country_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('country_key'),
    sa.UniqueConstraint('country_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_country')
    # ### end Alembic commands ###
