"""add account and transaction tables

Revision ID: 16ed64d2364c
Revises: b1a8bde0431c
Create Date: 2026-07-17 17:38:40.201855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ed64d2364c'
down_revision: Union[str, Sequence[str], None] = 'b1a8bde0431c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customer',
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kyc_status', sa.Boolean(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_key')
    )
    op.create_index(op.f('ix_dim_customer_customer_id'), 'dim_customer', ['customer_id'], unique=True)
    op.create_table('dim_account',
    sa.Column('account_key', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=30), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.PrimaryKeyConstraint('account_key')
    )
    op.create_index(op.f('ix_dim_account_account_number'), 'dim_account', ['account_number'], unique=True)
    op.create_index(op.f('ix_dim_account_customer_id'), 'dim_account', ['customer_id'], unique=False)
    op.create_table('fact_transaction',
    sa.Column('transaction_key', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=30), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('merchant_category', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_number'], ['dim_account.account_number'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.PrimaryKeyConstraint('transaction_key')
    )
    op.create_index(op.f('ix_fact_transaction_account_number'), 'fact_transaction', ['account_number'], unique=False)
    op.create_index(op.f('ix_fact_transaction_customer_id'), 'fact_transaction', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_transaction_transaction_id'), 'fact_transaction', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_transaction_transaction_id'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_customer_id'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_account_number'), table_name='fact_transaction')
    op.drop_table('fact_transaction')
    op.drop_index(op.f('ix_dim_account_customer_id'), table_name='dim_account')
    op.drop_index(op.f('ix_dim_account_account_number'), table_name='dim_account')
    op.drop_table('dim_account')
    op.drop_index(op.f('ix_dim_customer_customer_id'), table_name='dim_customer')
    op.drop_table('dim_customer')
    # ### end Alembic commands ###
