"""align alert transaction foreign key

Revision ID: 37bab6964f27
Revises: 8752fbfc1cbc
Create Date: 2026-09-04 18:33:50.338103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bab6964f27'
down_revision: Union[str, Sequence[str], None] = '8752fbfc1cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_alert', 'transaction_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'fact_alert', 'fact_transaction', ['transaction_id'], ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_alert', type_='foreignkey')
    op.alter_column('fact_alert', 'transaction_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
