"""add fact alert table

Revision ID: 6c660f41548a
Revises: da042b3889d4
Create Date: 2026-07-23 01:16:48.139073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c660f41548a'
down_revision: Union[str, Sequence[str], None] = 'da042b3889d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_alert',
    sa.Column('alert_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('alert_key')
    )
    op.create_index(op.f('ix_fact_alert_transaction_id'), 'fact_alert', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_alert_transaction_id'), table_name='fact_alert')
    op.drop_table('fact_alert')
    # ### end Alembic commands ###
