"""create case timeline table

Revision ID: 71d8e4956450
Revises: cf01b8a46052
Create Date: 2026-08-01 18:54:10.115476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d8e4956450'
down_revision: Union[str, Sequence[str], None] = 'cf01b8a46052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_timeline',
    sa.Column('timeline_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fact_case.case_id'], ),
    sa.PrimaryKeyConstraint('timeline_id')
    )
    op.create_index(op.f('ix_case_timeline_case_id'), 'case_timeline', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_timeline_case_id'), table_name='case_timeline')
    op.drop_table('case_timeline')
    # ### end Alembic commands ###
