"""create case alert mapping table

Revision ID: 79eae3ae26b5
Revises: 71d8e4956450
Create Date: 2026-08-02 10:52:19.629416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79eae3ae26b5'
down_revision: Union[str, Sequence[str], None] = '71d8e4956450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_case_alert',
    sa.Column('case_alert_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('alert_key', sa.Integer(), nullable=False),
    sa.Column('linked_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_key'], ['fact_alert.alert_key'], ),
    sa.ForeignKeyConstraint(['case_id'], ['fact_case.case_id'], ),
    sa.PrimaryKeyConstraint('case_alert_id')
    )
    op.create_index(op.f('ix_fact_case_alert_alert_key'), 'fact_case_alert', ['alert_key'], unique=False)
    op.create_index(op.f('ix_fact_case_alert_case_id'), 'fact_case_alert', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_case_alert_case_id'), table_name='fact_case_alert')
    op.drop_index(op.f('ix_fact_case_alert_alert_key'), table_name='fact_case_alert')
    op.drop_table('fact_case_alert')
    # ### end Alembic commands ###
