"""add alert unique constraint

Revision ID: a3166404a5a7
Revises: 6c660f41548a
Create Date: 2026-07-23 20:58:03.792875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3166404a5a7'
down_revision: Union[str, Sequence[str], None] = '6c660f41548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.execute("""
        DELETE FROM fact_alert a
        USING fact_alert b
        WHERE a.alert_key > b.alert_key
          AND a.transaction_id = b.transaction_id
          AND a.rule_name = b.rule_name;
    """)

    op.create_unique_constraint(
        "uq_transaction_rule",
        "fact_alert",
        ["transaction_id", "rule_name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_rule', 'fact_alert', type_='unique')
    # ### end Alembic commands ###
