"""create fact_case table

Revision ID: ae1475fb87b4
Revises: 041a369bc0c3
Create Date: 2026-07-24 20:22:04.316947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1475fb87b4'
down_revision: Union[str, Sequence[str], None] = '041a369bc0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_case',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('alert_key', sa.Integer(), nullable=False),
    sa.Column('investigator', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_key'], ['fact_alert.alert_key'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('alert_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_case')
    # ### end Alembic commands ###
