"""add assignment fields

Revision ID: cf01b8a46052
Revises: 56f2381597d5
Create Date: 2026-08-01 17:04:22.831103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf01b8a46052'
down_revision: Union[str, Sequence[str], None] = '56f2381597d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_case', sa.Column('assigned_by', sa.String(length=100), nullable=True))
    op.add_column('fact_case', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_case', 'assigned_at')
    op.drop_column('fact_case', 'assigned_by')
    # ### end Alembic commands ###
