"""add device dimension

Revision ID: da042b3889d4
Revises: 185498d77bc1
Create Date: 2026-07-23 00:49:12.268289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da042b3889d4'
down_revision: Union[str, Sequence[str], None] = '185498d77bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_device',
    sa.Column('device_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('operating_system', sa.String(length=50), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('device_key'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_device')
    # ### end Alembic commands ###
